### ISSUE TITLE
开源建议

### ISSUE THREAD

**Issue by userElaina** [LeMinerva/Dark-Souls-Documents#7]
你的 html 是用 word 之类的生成的吗？如果是的话，建议连同源文件/相关代码一起开源。

**Comment by LeMinerva** [comment]
因项目尚未完善，若不同经手人进行不同版本校正，易混淆不同差异的不完善校正版流传。目前经常见到包含过往错误的截图在传播，因转手次数过多，转手人难溯源到本项目最新情况，固仅保留在线版以便统一获悉最新更正，减少包含不同错误数量的迭代版本流传。
