### ISSUE TITLE
封坏护指+2的效果描述是否正确?

### ISSUE THREAD

**Issue by LoneWindG** [LeMinerva/Dark-Souls-Documents#9]
封坏护指+2的后半部分描述为铠甲/戒指降至65%, 但我查阅其他地方的说明效果后发现写的都是铠甲/戒指耐久损耗-45%, 照这个数值描述应该是铠甲/戒指降至55%? 不确定哪一个是正确的

**Comment by LeMinerva** [comment]
> 封坏护指+2的后半部分描述为铠甲/戒指降至65%, 但我查阅其他地方的说明效果后发现写的都是铠甲/戒指耐久损耗-45%, 照这个数值描述应该是铠甲/戒指降至55%? 不确定哪一个是正确的

Event(40120002, Default, function() {
    UnknownCommand10013002(30, 0, 0);
    ModifyStatMultiplicatively(MultiplicativeStatType.WeaponDegredationRate, 0, 0.5);
    ModifyStatMultiplicatively(MultiplicativeStatType.ArmorDegradationRate, 0, 0.65);
    ModifyStatMultiplicatively(MultiplicativeStatType.RingDegradationRate, 0, 0.65);
});
